// Source labels remain stable translation keys. Review copy changes in
// artifacts/COPY_REVIEW.md; quantities, process names and order values stay intact.
export const copyRefinements: readonly (readonly [
  section: string,
  source: string,
  english: string,
  thai: string,
  reason: string,
])[] = [
  [
    "Home / Hero",
    "Turn your ideas into retail-ready garments",
    "OEM garments, from idea to delivery",
    "ผลิตเสื้อผ้า OEM จากไอเดียถึงส่งมอบ",
    "ระบุบริการและขอบเขตงานทันที แทนคำสัญญาเชิงโฆษณาว่าสินค้าพร้อมขาย",
  ],
  [
    "Home / Introduction",
    "Thonburi Master provides OEM garment manufacturing through TM Apparel for domestic and international brands. We manage the process from brief and sample making to bulk production, QC, and delivery.",
    "Thonburi Master provides OEM garment manufacturing through TM Apparel for Thai and international brands. We work with you from the brief and sampling through bulk production, QC and delivery.",
    "Thonburi Master ให้บริการผลิตเสื้อผ้า OEM ผ่าน TM Apparel สำหรับแบรนด์ไทยและต่างประเทศ เราทำงานร่วมกับคุณตั้งแต่รับบรีฟและ Sampling ไปจนถึง Bulk Production, QC และส่งมอบ",
    "แสดงบทบาทพาร์ตเนอร์ด้วยงานที่ทำจริง และใช้ศัพท์กระบวนการที่ลูกค้า B2B คุ้นเคย",
  ],
  [
    "Home / Why us",
    "Your manufacturing partner from brief to delivery",
    "Your manufacturing partner from brief to delivery",
    "พาร์ตเนอร์การผลิตของคุณ ตั้งแต่บรีฟจนถึงส่งมอบ",
    "คงแนวคิดเดิมที่ชัดเจน ปรับภาษาไทยให้กระชับและเป็นธรรมชาติ",
  ],
  [
    "Home / Why us",
    "For us, good manufacturing starts before the sewing needle moves. By understanding the product design, quantity, usage, and delivery schedule, we ensure every step of the project aligns in the same direction.",
    "We review your design, quantity, intended use and delivery date with you before production. These details guide the work at each stage.",
    "ก่อนเริ่มผลิต เราทบทวน Design จำนวน การใช้งาน และกำหนดส่งมอบร่วมกับคุณ เพื่อใช้เป็นแนวทางทำงานในแต่ละขั้นตอน",
    "แทนภาพเปรียบเทียบและคำรับประกันด้วยการทำงานร่วมกันที่เข้าใจง่าย",
  ],
  [
    "Home / Starting points",
    "Whether you already have a product sample or just a preliminary idea, send us your details. Our team will help evaluate and discuss the next steps suited for your project.",
    "Have a sample, a design or an initial idea? Share what you have. Our team will review it with you and discuss the next step.",
    "มีตัวอย่าง แบบสินค้า หรือแค่ไอเดียเบื้องต้น ก็เริ่มพูดคุยได้ ส่งข้อมูลที่มีให้ทีมงานช่วยประเมินและหารือขั้นตอนถัดไปร่วมกับคุณ",
    "ลดความกังวลของแบรนด์ใหม่ พร้อมบอกวิธีเริ่มต้นอย่างชัดเจน",
  ],
  [
    "Home / Starting points",
    "Submission gateways",
    "Start your project",
    "เริ่มโปรเจกต์",
    "ใช้ภาษาที่ผู้เข้าชมเข้าใจทันทีแทนศัพท์ของระบบ",
  ],
  [
    "Home / Starting points",
    "Stage 01 / Concept",
    "Starting point 01 / Idea",
    "จุดเริ่มต้น 01 / ไอเดีย",
    "สองการ์ดเป็นทางเลือกเริ่มต้น ไม่ใช่ขั้นตอนที่ต้องทำตามลำดับ",
  ],
  [
    "Home / Starting points",
    "Stage 02 / Production",
    "Starting point 02 / design or reference",
    "จุดเริ่มต้น 02 / แบบหรือภาพอ้างอิง",
    "สื่อความพร้อมที่ต้องใช้จริง โดยไม่ทำให้เข้าใจว่าสามารถเริ่มผลิตทันที",
  ],
  [
    "Home / Starting points",
    "Ready to production",
    "Ready for review",
    "พร้อมให้ทีมประเมิน",
    "แก้ไวยากรณ์อังกฤษและแยกการประเมินออกจากการเริ่มผลิต",
  ],
  [
    "Home / Starting points",
    "Early product idea",
    "Have a design or reference?",
    "มีแบบหรือภาพอ้างอิงแล้ว",
    "ทำให้สองทางเลือกแตกต่างกันชัดเจน",
  ],
  [
    "Home / Starting points",
    "Tell us about the product you want to make, target audience, or desired outcome to help define requirements before production.",
    "Tell us what you want to make, who it is for and how it will be used. We can review the production requirements together.",
    "บอกเราว่าต้องการผลิตอะไร สำหรับใคร และใช้งานอย่างไร เพื่อช่วยกันทบทวนรายละเอียดก่อนเริ่มผลิต",
    "ใช้คำถามที่ตอบได้ง่ายแทนการถามผลลัพธ์แบบกว้าง ๆ",
  ],
  [
    "Home / Starting points",
    "Send us a product sample, reference image, sketch, or design, along with the desired quantity and deadline.",
    "Share your sample, reference images, sketch or design, together with the quantity and required delivery date.",
    "ส่งตัวอย่าง ภาพอ้างอิง สเก็ตช์ หรือ Design ที่มี พร้อมจำนวนและวันที่ต้องการส่งมอบ",
    "บอกข้อมูลที่จำเป็นอย่างตรงไปตรงมา โดยคงรายละเอียดเดิม",
  ],
  [
    "Shared / Factory visit CTA",
    "Start working with us today, we are ready to support you",
    "Let’s discuss your garment project",
    "พูดคุยเรื่องโปรเจกต์เสื้อผ้าของคุณ",
    "ลดแรงกดดันให้เริ่มงานทันที และชวนเข้าสู่การพูดคุยที่เหมาะกับ CTA",
  ],
  [
    "Shared / Factory visit",
    "We welcome executives, product development teams, or brand owners to visit our factory production process directly. Please make an appointment in advance to discuss your brand's needs and tour our factory to understand our workflow before starting production.",
    "Visit the factory to see how we work and discuss your brand’s production requirements. We welcome brand owners, product development teams and executives by appointment.",
    "นัดเยี่ยมชมโรงงานเพื่อดูขั้นตอนการทำงานและพูดคุยเรื่องการผลิตของแบรนด์คุณ เรายินดีต้อนรับเจ้าของแบรนด์ ทีมพัฒนาสินค้า และผู้บริหาร โดยนัดหมายล่วงหน้า",
    "ลดประโยคซ้ำและเริ่มจากประโยชน์ที่ลูกค้าจะได้รับ โดยคงเงื่อนไขนัดหมาย",
  ],
  [
    "Shared / Customers",
    "At TM Apparel, we have experience manufacturing garments for leading Thai shopping malls, reflecting our understanding of working with retail clients and brands with varying requirements.",
    "TM Apparel has experience manufacturing garments for Thai retail clients. We work with each customer’s product and production requirements.",
    "TM Apparel มีประสบการณ์ผลิตเสื้อผ้าให้ลูกค้าค้าปลีกในไทย โดยทำงานตามความต้องการด้านสินค้าและการผลิตของลูกค้าแต่ละราย",
    "ตัดคำว่าชั้นนำและข้อสรุปเชิงโอ้อวด ใช้ประสบการณ์เดิมเป็นฐานความน่าเชื่อถือ",
  ],
  [
    "About / Introduction",
    "TM Apparel is part of Thonburi Master, providing OEM garment manufacturing for Thai and international brands. We manage each stage, from reviewing the brief and selecting materials to sample development, bulk production, QC and delivery. We plan with our clients and use approved samples to guide production so that sizes, shapes and details match each brand's requirements.",
    "TM Apparel is part of Thonburi Master. We provide OEM garment manufacturing for Thai and international brands, from brief review and material selection through sampling, bulk production, QC and delivery.",
    "TM Apparel เป็นส่วนหนึ่งของ Thonburi Master ให้บริการผลิตเสื้อผ้า OEM สำหรับแบรนด์ไทยและต่างประเทศ ตั้งแต่ทบทวนบรีฟและเลือก Material ไปจนถึง Sampling, Bulk Production, QC และส่งมอบ",
    "แยกข้อมูลบริษัทออกจากวิธีทำงาน ลดเนื้อหาซ้ำกับย่อหน้าถัดไป",
  ],
  [
    "About / Collaboration",
    "We plan materials and sample approval with our customers. Cutting, sewing and pressing teams review the design together before production to align sizes, shapes, techniques and quality checkpoints with the agreed details.",
    "We plan materials and sample approval with you. Before production, our cutting, sewing and pressing teams review the approved design together, including sizes, shapes, techniques and QC checkpoints.",
    "เราวางแผนเลือก Material และอนุมัติตัวอย่างร่วมกับคุณ ก่อนเริ่มผลิต ทีมตัด เย็บ และรีดจะทบทวนแบบที่อนุมัติร่วมกัน ทั้งไซซ์ ทรง เทคนิค และจุดตรวจ QC",
    "ทำให้ลูกค้าเห็นว่าตัวอย่างที่อนุมัติเชื่อมกับการทำงานของทีมอย่างไร",
  ],
  [
    "About / Hero",
    "For Thai and international brands",
    "For Thai and international brands",
    "สำหรับแบรนด์ไทยและต่างประเทศ",
    "ใช้คำว่าแบรนด์ที่อ่านเป็นธรรมชาติในภาษาไทย โดยไม่จำเป็นต้องใช้ English ทุกคำ",
  ],
  [
    "About / History",
    "Manufacturing experience that grows with your brand",
    "Our manufacturing experience",
    "ประสบการณ์ด้านการผลิตของเรา",
    "ให้หัวข้อทำหน้าที่แนะนำประวัติบริษัท แทนคำสัญญาการเติบโตของลูกค้า",
  ],
  [
    "About / History",
    "Company history",
    "Company history",
    "ประวัติบริษัท",
    "ตัดหัวข้อสองภาษาที่ซ้ำใน locale ไทย",
  ],
  [
    "About / Audit",
    "Big C's 2025 factory assessment by NSF Asia-Pacific recorded Grade A, 94.61% and Pass. The supplied Lotus’s assessment by TÜV Rheinland recorded Blue Tier against its Non-Food Standard v.1. These are partner audit results; ask our team for the current assessment period and relevant factory document details.",
    "Big C’s 2025 factory assessment by NSF Asia-Pacific recorded Grade A, 94.61% and Pass. The available Lotus’s assessment by TÜV Rheinland recorded Blue Tier under its Non-Food Standard v.1. These are customer audit results. Contact our team to confirm the current assessment period and request relevant factory documents.",
    "ผลประเมินโรงงานของ Big C ปี 2025 โดย NSF Asia-Pacific ระบุ Grade A, 94.61% และ Pass ส่วนผลประเมิน Lotus’s ที่มีโดย TÜV Rheinland ระบุ Blue Tier ตาม Non-Food Standard v.1 ข้อมูลนี้เป็นผล audit จากลูกค้า ติดต่อทีมงานเพื่อยืนยันช่วงเวลาประเมินปัจจุบันและขอเอกสารโรงงานที่เกี่ยวข้อง",
    "แบ่งประโยคให้อ่านง่าย รักษาผลและช่วงเวลา audit โดยไม่กล่าวว่าเป็น Certification ปัจจุบัน",
  ],
  [
    "About / Audit",
    "Audit periods shown where supplied",
    "Check the assessment period",
    "ตรวจสอบช่วงเวลาประเมิน",
    "เปลี่ยนคำอธิบายการจัดทำข้อมูลให้เป็นสิ่งที่ผู้ซื้อควรพิจารณา",
  ],
  [
    "About / People and workplace",
    "Our workforce provisions include wages in line with legal requirements, social security and annual health checks. Staff support includes attendance incentives, reduced-rate rooms, drinking water, company meals and annual rice distribution. Fire drills, fire equipment, first aid and warning signs support workplace preparedness; solar panels contribute to energy supply.",
    "We provide wages in line with legal requirements, social security and annual health checks. Staff welfare includes attendance incentives, reduced-rate accommodation, drinking water, company meals and annual rice distribution. Fire drills, fire equipment, first aid and warning signs support workplace preparedness. Solar panels contribute to the factory’s energy supply.",
    "เราดูแลค่าจ้างตามกฎหมาย ประกันสังคม และการตรวจสุขภาพประจำปี สวัสดิการมีทั้งเบี้ยขยัน ที่พักราคาลดหย่อน น้ำดื่ม อาหารบริษัท และการแจกข้าวสารประจำปี โรงงานมีการซ้อมดับเพลิง อุปกรณ์ดับเพลิง ปฐมพยาบาล และป้ายเตือนเพื่อเตรียมความพร้อม รวมถึงใช้แผง Solar เป็นส่วนหนึ่งของแหล่งพลังงาน",
    "แบ่งข้อมูลคน ความปลอดภัย และพลังงานออกเป็นประโยคสั้น โดยไม่เพิ่มข้ออ้างเรื่องมาตรฐาน",
  ],
  [
    "About / People and workplace",
    "Solar panels contribute to the factory's energy supply. Organic or recycled fabric sourcing can be discussed by specification, minimum quantity and supplier availability.",
    "Solar panels contribute to the factory’s energy supply. Ask us about organic or recycled fabric options; availability depends on specification, MOQ and sourcing.",
    "โรงงานใช้แผง Solar เป็นส่วนหนึ่งของแหล่งพลังงาน สอบถามทางเลือกผ้า Organic หรือ Recycled ได้ โดยขึ้นอยู่กับ Specification, MOQ และการจัดหา",
    "คงข้อจำกัดการจัดหาผ้า และไม่เพิ่มคำกล่าวอ้างด้านผลกระทบสิ่งแวดล้อม",
  ],
  [
    "About / Team",
    "Discipline:",
    "Role:",
    "หน้าที่:",
    "ใช้คำที่ตรงกับบทบาททีมงานมากกว่า discipline",
  ],
  [
    "Our Work / Hero",
    "Your trust, delivered as finished garments",
    "Garment production to your approved design",
    "ผลิตเสื้อผ้าตามแบบที่คุณอนุมัติ",
    "แทน slogan เรื่องความไว้วางใจด้วยขอบเขตบริการที่ตรวจสอบได้",
  ],
  [
    "Our Work / Introduction",
    "TM Apparel manufactures garments to customer-approved designs and specifications, from fabric selection, sampling, cutting, sewing and decoration to quality checks and delivery preparation, aligning materials, sizes and product details with each brand's requirements.",
    "TM Apparel manufactures garments to your approved design and specification. We manage fabric selection, sampling, cutting, sewing and decoration, followed by QC and delivery preparation. Materials, sizes and garment details are agreed for your project.",
    "TM Apparel ผลิตเสื้อผ้าตาม Design และ Specification ที่คุณอนุมัติ เราดูแลตั้งแต่เลือกผ้า Sampling ตัด เย็บ และตกแต่ง ไปจนถึง QC และเตรียมส่งมอบ โดยตกลง Material ไซซ์ และรายละเอียดสินค้าร่วมกันสำหรับโปรเจกต์ของคุณ",
    "แยกประโยคยาวและระบุจุดที่ตกลงกับลูกค้า โดยคงความหมายทางเทคนิค",
  ],
  [
    "Our Work / CTA",
    "Is it time for your next batch?",
    "Planning your next production run?",
    "กำลังวางแผนผลิตคอลเลกชันถัดไปอยู่ไหม",
    "ปรับคำชวนที่ฟังเร่งเร้าให้สอดคล้องกับการวางแผนของลูกค้า",
  ],
  [
    "Our Work / CTA",
    "Start with fabric or a design that suits your brand",
    "Discuss the fabric and design for your brand",
    "พูดคุยเรื่องผ้าและ Design สำหรับแบรนด์ของคุณ",
    "ชวนหารือเรื่องงานที่เป็นรูปธรรมแทนคำว่าตอบโจทย์",
  ],
  [
    "Our Work / Page title",
    "Our work, delivered trust",
    "Our work & capabilities",
    "ผลงานและขอบเขตการผลิต",
    "ชื่อหน้าชัดเจนและสอดคล้องกับเนื้อหา มากกว่าคำโฆษณา",
  ],
  [
    "OEM Process / Introduction",
    "Thonburi Master manages OEM garment production through TM Apparel, from receiving details and assessing the project to sample making, bulk production, QC, and delivery, ensuring clarity for each project from the start.",
    "Plan your OEM garment project with Thonburi Master through TM Apparel. The six main steps cover brief review, quotation, sampling, bulk production, QC and delivery.",
    "วางแผนผลิตเสื้อผ้า OEM ร่วมกับ Thonburi Master ผ่าน TM Apparel ใน 6 ขั้นตอนหลัก ตั้งแต่ทบทวนบรีฟ เสนอราคา Sampling, Bulk Production, QC จนถึงส่งมอบ",
    "อธิบายภาพรวมที่ลูกค้าใช้วางแผนได้ โดยคงกระบวนการเดิม 6 ขั้นตอน",
  ],
  [
    "OEM Process / Hero",
    "Turn your ideas",
    "Develop your garment idea",
    "พัฒนาไอเดียเสื้อผ้าของคุณ",
    "ระบุสิ่งที่ลูกค้ากำลังทำแทนคำโฆษณากว้าง ๆ",
  ],
  [
    "OEM Process / Hero",
    "Into retail-ready products through a clear process",
    "Through six main production steps",
    "ผ่าน 6 ขั้นตอนหลักในการผลิต",
    "เชื่อมกับกระบวนการบนหน้า โดยไม่รับประกันสถานะพร้อมขาย",
  ],
  [
    "OEM Process / Hero",
    "From ideas to retail-ready products",
    "From garment idea to delivery",
    "จากไอเดียเสื้อผ้าจนถึงส่งมอบ",
    "ใช้ผลลัพธ์ที่อยู่ในขอบเขตบริการจริง",
  ],
  [
    "OEM Process / Hero",
    "Synchronised from requirement to delivery",
    "Plan each step from brief to delivery",
    "วางแผนแต่ละขั้นตอน ตั้งแต่บรีฟจนถึงส่งมอบ",
    "ใช้ภาษาทำงานร่วมกันแทนศัพท์ที่ดูเป็นระบบมากเกินไป",
  ],
  [
    "OEM Process / Brief",
    "Send your design or reference images, quantity, sizes, colours and delivery date. If you have a physical sample, send it for the team to review.",
    "Share your design or reference images, quantity, sizes, colours and required delivery date. If you have a physical sample, send it for review.",
    "ส่ง Design หรือภาพอ้างอิง พร้อมจำนวน ไซซ์ สี และวันที่ต้องการส่งมอบ หากมีตัวอย่างจริง ส่งให้ทีมงานพิจารณาได้",
    "บอกสิ่งที่ลูกค้าต้องเตรียมอย่างกระชับ",
  ],
  [
    "OEM Process / Sampling",
    "Select fabric, colours and trims. Review sample measurements, fit and details, then approve the sample before bulk production.",
    "Agree the fabric, colours and trims with the team. Review the sample’s measurements, fit and details before approving it for bulk production.",
    "เลือกผ้า สี และวัสดุตกแต่งร่วมกับทีมงาน ตรวจขนาด Fit และรายละเอียดของตัวอย่าง แล้วอนุมัติก่อนเริ่ม Bulk Production",
    "ชี้จุดมีส่วนร่วมและการอนุมัติของลูกค้า โดยรักษาลำดับขั้นตอน",
  ],
  [
    "OEM Process / FAQ",
    "The supplied sample fee is THB 1,000–2,000. It can be credited as a discount when you place a production order; confirm the amount and terms with the team.",
    "The sample fee is THB 1,000–2,000 and can be credited towards a production order. Confirm the fee and credit terms with our team.",
    "ค่าทำตัวอย่างอยู่ที่ 1,000–2,000 บาท และนำไปเป็นส่วนลดเมื่อสั่งผลิตได้ กรุณายืนยันค่าใช้จ่ายและเงื่อนไขกับทีมงาน",
    "ตัดคำว่าตามข้อมูลที่ได้รับซึ่งเป็นภาษารายงานภายใน คงราคาและเงื่อนไขยืนยัน",
  ],
  [
    "OEM Process / FAQ",
    "Allow approximately 7–14 days per sample round and 30–45 days for bulk production, depending on fabric ordering and quantity. QC and packing/delivery each take about 2–5 days. These estimates are not a combined delivery guarantee.",
    "Sampling takes approximately 7–14 days per round. Bulk production takes approximately 30–45 days, depending on fabric ordering and quantity. Allow about 2–5 days each for QC and packing/delivery. Confirm the overall schedule with our team; these stage estimates are not a guaranteed delivery date.",
    "Sampling ใช้เวลาประมาณ 7–14 วันต่อรอบ ส่วน Bulk Production ประมาณ 30–45 วัน ขึ้นอยู่กับการสั่งผ้าและจำนวน เผื่อเวลาสำหรับ QC และการแพ็ก/ส่งมอบขั้นละประมาณ 2–5 วัน กรุณายืนยันกำหนดการรวมกับทีมงาน ระยะเวลาแต่ละขั้นเป็นประมาณการ ไม่ใช่กำหนดส่งมอบที่รับประกัน",
    "แยกระยะเวลาแต่ละขั้นให้ scan ได้ พร้อมบอกวิธียืนยัน Lead Time โดยไม่เพิ่มคำรับประกัน",
  ],
  [
    "OEM Process / CTA",
    "Ready to start working together?",
    "Ready to discuss your project?",
    "พร้อมพูดคุยเรื่องโปรเจกต์ของคุณไหม",
    "ให้ CTA เป็นมิตรและเริ่มจากการหารือ ไม่กดดันให้ตกลงผลิต",
  ],
  [
    "OEM Process / QC",
    "// Be trusted",
    "// Quality checks",
    "// การตรวจคุณภาพ",
    "ระบุหน้าที่ของส่วนเนื้อหาแทนคำชวนให้เชื่อใจ",
  ],
  [
    "OEM Process / FAQ",
    "// Inquiry resolution",
    "// Your questions",
    "// ตอบข้อสงสัยของคุณ",
    "ลดศัพท์องค์กรและสื่อจากมุมมองผู้เข้าชม",
  ],
  [
    "Shared / Materials",
    "Organic or recycled fabrics depend on specification, minimum quantity and sourcing; GOTS, GRS or RCS fabric documentation can be requested.",
    "Organic or recycled fabric options depend on specification, MOQ and sourcing. Ask our team for relevant GOTS, GRS or RCS fabric documentation.",
    "ทางเลือกผ้า Organic หรือ Recycled ขึ้นอยู่กับ Specification, MOQ และการจัดหา สอบถามเอกสารผ้า GOTS, GRS หรือ RCS ที่เกี่ยวข้องได้กับทีมงาน",
    "รักษาชื่อมาตรฐานและข้อจำกัด โดยไม่ทำให้เข้าใจว่าโรงงานได้รับ Certification เหล่านี้",
  ],
  [
    "Shared / Materials",
    "Lightweight options for sports and teamwear. Discuss breathability, drying performance and recycled polyester.",
    "Lightweight fabric options for sportswear and teamwear. Discuss breathability, drying performance and recycled polyester with our team.",
    "ผ้าน้ำหนักเบาสำหรับเสื้อกีฬาและเสื้อทีม พูดคุยกับทีมงานเรื่องการระบายอากาศ การแห้ง และ Recycled polyester",
    "ปรับภาษาไทยที่แปลคำว่าการแห้งไม่ลื่นไหล โดยคงคุณสมบัติที่ต้องหารือ",
  ],
  [
    "Shared / Materials",
    "Textured fabric for cargo and outdoor trousers. Water repellency depends on specification and finish.",
    "Textured fabric for cargo and outdoor trousers. Water repellency depends on the fabric specification and finish.",
    "ผ้ามีพื้นผิวสำหรับกางเกง Cargo และกางเกงเดินป่า คุณสมบัติสะท้อนน้ำขึ้นอยู่กับ Specification ของผ้าและการตกแต่งผิว",
    "ทำให้ชัดว่าคุณสมบัติสะท้อนน้ำต้องตรวจตามผ้าที่ใช้จริง",
  ],
  [
    "Shared / Services",
    "In-house finishing",
    "In-house finishing",
    "งาน Finishing ภายในโรงงาน",
    "รักษาศัพท์กระบวนการที่แม่นยำแทนคำแปลตกแต่งสำเร็จที่ไม่เป็นธรรมชาติ",
  ],
  [
    "Shared / Services",
    "Fastenings",
    "Fastenings",
    "อุปกรณ์ยึดและปิดเสื้อผ้า",
    "แก้คำไทยให้สื่อถึงกระดุมและตัวปิดเสื้อผ้าได้ชัดขึ้น",
  ],
  [
    "Garment Style References / Introduction",
    "Explore garment groups and product types for your next collection. Style illustrations and photo references are starting points for discussing your own design.",
    "Browse garment groups and styles for your next collection. Use the illustrations and photo references to discuss your own design with our team.",
    "เลือกดูกลุ่มเสื้อผ้าและรูปแบบสำหรับคอลเลกชันถัดไป ใช้ภาพประกอบและภาพถ่ายอ้างอิงเป็นจุดเริ่มต้นพูดคุยเรื่อง Design ของคุณกับทีมงาน",
    "บอกว่าลูกค้าใช้ภาพอ้างอิงอย่างไร โดยไม่อ้างว่าเป็นผลงานลูกค้าจริง",
  ],
  [
    "Garment Style References / Details",
    "Fabric, decoration, sizing and production details are agreed for your project.",
    "Agree the fabric, decoration, sizes and production details with our team for your project.",
    "ตกลงผ้า การตกแต่ง ไซซ์ และรายละเอียดการผลิตกับทีมงานสำหรับโปรเจกต์ของคุณ",
    "เปลี่ยนประโยค passive เป็นขั้นตอนที่ลูกค้าร่วมทำได้",
  ],
  [
    "Garment Style References / Empty state",
    "No matching references published yet.",
    "No references match these filters yet.",
    "ยังไม่มีแบบอ้างอิงที่ตรงกับตัวกรองนี้",
    "บอกสถานะผลลัพธ์โดยไม่ทำให้เข้าใจว่าโรงงานไม่รับผลิตประเภทนี้",
  ],
  [
    "Garment Style References / CTA",
    "Discuss your garment",
    "Discuss your design",
    "พูดคุยเรื่องแบบเสื้อผ้าของคุณ",
    "ทำให้สิ่งที่ต้องการให้ลูกค้าติดต่อมาชัดเจน",
  ],
  [
    "Technical Insights / Introduction",
    "Start with the product you want to make. Review fabric feel, shape, movement and finishing options, then agree the materials, sizes and details through a sample before bulk production.",
    "Choose materials around the garment’s intended use. Review fabric feel, shape, movement and finishing options, then confirm materials, sizes and details through sampling before bulk production.",
    "เลือก Material ให้เหมาะกับการใช้งานเสื้อผ้า พิจารณาสัมผัสผ้า ทรง การเคลื่อนไหว และงาน Finishing แล้วใช้ Sampling เพื่อยืนยัน Material ไซซ์ และรายละเอียดก่อน Bulk Production",
    "เริ่มจากการตัดสินใจของลูกค้า และเชื่อมข้อมูลเทคนิคกับการอนุมัติตัวอย่าง",
  ],
  [
    "Technical Insights / Summary",
    "Engineering summary / Three core takeaways",
    "Fabric selection / Three key points",
    "การเลือกผ้า / 3 ประเด็นสำคัญ",
    "ลดศัพท์ที่ทำให้เนื้อหาพื้นฐานดูซับซ้อนเกินจริง",
  ],
  [
    "Technical Insights / Tools",
    "Practical tools & specification calculators",
    "Tools for your production brief",
    "เครื่องมือเตรียมบรีฟการผลิต",
    "หัวข้อเดิมเป็นพหูพจน์ทั้งที่มี calculator เพียงตัวเดียว ใช้ขอบเขตเครื่องมือที่มีจริง",
  ],
  [
    "Technical Insights / Tools",
    "Sizing matrix spec sheet",
    "Size & measurement spec sheet",
    "Spec sheet สำหรับไซซ์และขนาด",
    "ใช้คำที่อธิบายสิ่งที่ลูกค้าจะได้รับได้ทันที",
  ],
  [
    "Technical Insights / Tools",
    "Technical dossier checklist",
    "Production brief checklist",
    "Checklist เตรียมบรีฟการผลิต",
    "ลดศัพท์ dossier ที่ไม่จำเป็นสำหรับผู้เริ่มต้น",
  ],
  [
    "Technical Insights / Tools",
    "Request dossier (PDF)",
    "Request checklist (PDF)",
    "ขอ Checklist (PDF)",
    "ให้ชื่อ CTA สอดคล้องกับเนื้อหาและคงรูปแบบไฟล์เดิม",
  ],
  [
    "Technical Insights / Tools",
    "Open calculator suite",
    "Open shrinkage calculator",
    "เปิดเครื่องคำนวณการหดตัวของผ้า",
    "ระบุเครื่องมือที่เปิดจริง แทนการอ้างว่ามีชุดเครื่องมือหลายรายการ",
  ],
  [
    "Technical Insights / Library",
    "Bulletin topics",
    "Guide topics",
    "หัวข้อแนวทางการผลิต",
    "ใช้ชื่อที่ตรงกับเนื้อหาและเป็นมิตรต่อผู้อ่าน",
  ],
  [
    "Technical Insights / Library",
    "Search technical bulletins",
    "Search production guides",
    "ค้นหาแนวทางการผลิต",
    "ลดศัพท์แบบจดหมายข่าวและให้คำเรียกเนื้อหาสม่ำเสมอ",
  ],
  [
    "Technical Insights / Library",
    "Curated technical compendium",
    "Production planning guides",
    "แนวทางวางแผนการผลิต",
    "ตัดศัพท์โอ่อ่าที่ไม่ได้ช่วยให้ลูกค้าเข้าใจเนื้อหา",
  ],
  [
    "Technical Insights / Library",
    "All planning excerpts (9)",
    "All guides (1)",
    "แนวทางทั้งหมด (1)",
    "มีเนื้อหาเพียงเรื่องเดียวที่ถูกแสดงซ้ำ 9 ครั้ง จึงแสดงรายการจริงเพียงครั้งเดียว",
  ],
  [
    "Technical Insights / Library",
    "Showing {count} planning excerpts",
    "Showing {count} guides",
    "แสดงแนวทาง {count} รายการ",
    "ให้คำเรียกและจำนวนตรงกับรายการเนื้อหาจริง โดยรักษาตัวแปรระบบ",
  ],
  [
    "Technical Insights / Library",
    "No planning excerpts match this filter.",
    "No guides match these filters.",
    "ไม่พบแนวทางที่ตรงกับตัวกรองนี้",
    "ทำให้ข้อความผลการค้นหาสั้นและสม่ำเสมอ",
  ],
  [
    "Start Your Project / Introduction",
    "Tell us what you want to make, how many pieces you need, and when you need them. Our team will review your brief and contact you to discuss the next step.",
    "Tell us what you want to make, the quantity and your required delivery date. Our team will review your brief and contact you to discuss the next step.",
    "บอกเราว่าต้องการผลิตอะไร จำนวนเท่าไร และต้องการส่งมอบเมื่อไร ทีมงานจะทบทวนบรีฟและติดต่อกลับเพื่อหารือขั้นตอนถัดไป",
    "ชี้แจงวันที่ต้องการให้หมายถึงส่งมอบ และบอกสิ่งที่จะเกิดหลังส่งข้อมูล",
  ],
  [
    "Start Your Project / Form",
    "Spec evaluation terminal",
    "Project brief form",
    "แบบฟอร์มบรีฟโปรเจกต์",
    "ใช้ชื่อหน้าที่จริงของแบบฟอร์มแทนภาษาระบบ",
  ],
  [
    "Start Your Project / Form",
    "Structured CAD / BOM intake",
    "Design files & production details",
    "ไฟล์ Design และรายละเอียดการผลิต",
    "ไม่ทำให้ลูกค้าใหม่เข้าใจว่าต้องมี CAD หรือ BOM จึงเริ่มติดต่อได้",
  ],
  [
    "Start Your Project / Form",
    "Required credentials",
    "Contact details",
    "ข้อมูลติดต่อ",
    "ข้อมูลนี้ไม่ใช่ credentials สำหรับเข้าระบบ",
  ],
  [
    "Start Your Project / Form",
    "Preferred communication protocol",
    "Preferred contact channel",
    "ช่องทางติดต่อที่สะดวก",
    "ใช้ชื่อที่บอกสิ่งให้เลือกตรง ๆ",
  ],
  [
    "Start Your Project / Form",
    "Categorisation",
    "Your garment",
    "สินค้าที่ต้องการผลิต",
    "เน้นข้อมูลของลูกค้าแทนกระบวนการจัดหมวดหมู่ภายใน",
  ],
  [
    "Start Your Project / Form",
    "Primary apparel category",
    "Garment category",
    "ประเภทเสื้อผ้า",
    "กระชับโดยคงความหมายของประเภทสินค้าที่เลือก",
  ],
  [
    "Start Your Project / Form",
    "Technical readiness / current starting point *",
    "Your starting point *",
    "จุดเริ่มต้นของคุณ *",
    "ไม่ใช้ระดับความพร้อมทางเทคนิคเป็นเกณฑ์กีดกันลูกค้าใหม่",
  ],
  [
    "Start Your Project / Form",
    "Level 01",
    "Option 01",
    "ทางเลือก 01",
    "สองรายการเป็นทางเลือก ไม่ใช่ระดับความสามารถของลูกค้า",
  ],
  [
    "Start Your Project / Form",
    "Level 02",
    "Option 02",
    "ทางเลือก 02",
    "สองรายการเป็นทางเลือก ไม่ใช่ระดับความสามารถของลูกค้า",
  ],
  [
    "Start Your Project / Form",
    "BOM parameters",
    "Quantity & delivery date",
    "จำนวนและกำหนดส่งมอบ",
    "เนื้อหาส่วนนี้ถามจำนวนและเวลา ไม่ได้ให้กรอก BOM",
  ],
  [
    "Start Your Project / Form",
    "Select pilot or mass run capacity",
    "Select an estimated quantity",
    "เลือกจำนวนผลิตโดยประมาณ",
    "หลีกเลี่ยงการสื่อว่ารับ pilot run ทุกขนาดจากเพียงตัวเลือกในแบบฟอร์ม",
  ],
  [
    "Start Your Project / Form",
    "Target handover / on-port window",
    "Required delivery date / arrival at port",
    "กำหนดส่งมอบ / วันที่ต้องการให้ถึงท่าเรือ",
    "คงความหมายเรื่องท่าเรือ แต่เปลี่ยนภาษาที่กำกวมให้เข้าใจง่าย",
  ],
  [
    "Start Your Project / Upload",
    "Drag & drop specification assets",
    "Drop your design or reference files here",
    "ลากไฟล์ Design หรือภาพอ้างอิงมาวางที่นี่",
    "ใช้คำที่ตรงกับสิ่งที่ลูกค้าจะอัปโหลด",
  ],
  [
    "Start Your Project / Upload",
    "Browse machine directory",
    "Choose files",
    "เลือกไฟล์",
    "CTA สั้นและตรงหน้าที่ของปุ่ม",
  ],
  [
    "Start Your Project / Upload",
    "Attached technical documentation [{count} files]",
    "Attachments [{count} files]",
    "ไฟล์แนบ [{count} ไฟล์]",
    "ไฟล์อาจเป็นภาพอ้างอิง ไม่จำเป็นต้องเป็นเอกสารเทคนิค",
  ],
  [
    "Start Your Project / NDA",
    "Request bilateral mutual NDA:",
    "Request a mutual NDA:",
    "ขอ NDA ระหว่างทั้งสองฝ่าย:",
    "ตัดคำซ้ำ bilateral/mutual โดยรักษาความหมายการขอข้อตกลง",
  ],
  [
    "Start Your Project / NDA",
    "I request an NDA before sharing confidential pattern engineering specifications.",
    "I would like an NDA before sharing confidential pattern specifications.",
    "ฉันต้องการ NDA ก่อนส่ง Specification ของ Pattern ที่เป็นความลับ",
    "ตัดศัพท์ engineering ที่ไม่จำเป็น โดยไม่เปลี่ยนขอบเขตความลับ",
  ],
  [
    "Start Your Project / Submission",
    "Ready for feasibility audit",
    "Ready to share your brief?",
    "พร้อมส่งบรีฟให้ทีมงานพิจารณาไหม",
    "ไม่เรียกการประเมินโปรเจกต์ว่า audit ซึ่งอาจทำให้เข้าใจผิด",
  ],
  [
    "Start Your Project / Submission",
    "Production engineering review · Project brief intake",
    "Project brief · Production review",
    "บรีฟโปรเจกต์ · ประเมินงานผลิต",
    "คงหน้าที่ของขั้นตอนโดยลดภาษาระบบ",
  ],
  [
    "Start Your Project / Submission",
    "Submit project brief for feasibility review",
    "Send your project brief",
    "ส่งบรีฟโปรเจกต์",
    "ปุ่มกระชับ ส่วนคำอธิบายขั้นตอนประเมินมีอยู่ในหน้าแล้ว",
  ],
  [
    "Start Your Project / Submission",
    "Human pattern engineers only",
    "Our team reviews your brief",
    "ทีมงานจะพิจารณาบรีฟของคุณ",
    "ลดข้ออ้างเรื่องคุณสมบัติและความเป็นเอกสิทธิ์ของผู้ตรวจสอบที่ไม่มีหลักฐานเพิ่ม",
  ],
  [
    "Contact / Hero",
    "Talk to our team about your garment project & production requirements",
    "Talk to us about your garment project",
    "พูดคุยกับเราเรื่องโปรเจกต์เสื้อผ้าของคุณ",
    "Hero สั้นและอ่านได้ทันที โดยรายละเอียดการผลิตอยู่ในย่อหน้ารอง",
  ],
  [
    "Contact / Channels",
    "Direct desk channels",
    "Contact our team directly",
    "ติดต่อทีมงานโดยตรง",
    "ลดคำเรียกโต๊ะทำงานที่ไม่ช่วยผู้เข้าชม",
  ],
  [
    "Contact / Channels",
    "Direct channels roster",
    "Direct contact channels",
    "ช่องทางติดต่อโดยตรง",
    "ใช้ชื่อเนื้อหาที่ตรงและอ่านง่าย",
  ],
  [
    "Contact / Form",
    "Desk transmission terminal",
    "Send an enquiry",
    "ส่งคำสอบถาม",
    "ระบุสิ่งที่ลูกค้าทำได้ แทนศัพท์เทคโนโลยี",
  ],
  [
    "Contact / Form",
    "For detailed BOM evaluations and CAD uploads, please use the structured",
    "To share your design files or detailed BOM and CAD information, use the",
    "หากต้องการส่งไฟล์ Design หรือข้อมูล BOM และ CAD ให้ใช้แบบฟอร์ม",
    "ชี้ความต่างระหว่างแบบฟอร์มโดยยังรักษาการรองรับข้อมูลเทคนิค",
  ],
  [
    "Contact / Form",
    "brief terminal. Use this desk form for commercial inquiries, factory visit requests, and general partnership dialog.",
    "Form. Use this form for quotation enquiries, factory visits or partnership discussions.",
    "ส่วนแบบฟอร์มนี้ใช้สอบถามราคา นัดเยี่ยมชมโรงงาน หรือพูดคุยเรื่องความร่วมมือ",
    "แก้สำนวนที่แข็งและไวยากรณ์ให้ประโยคที่ประกอบกับลิงก์อ่านต่อเนื่อง",
  ],
  [
    "Contact / Form",
    "Official work email",
    "Contact email",
    "Email สำหรับติดต่อ",
    "ไม่ทำให้แบรนด์ใหม่เข้าใจว่าต้องมี Email บริษัทจึงติดต่อได้",
  ],
  [
    "Contact / Form",
    "Select country / operational jurisdiction",
    "Select a country",
    "เลือกประเทศ",
    "คำว่า jurisdiction ไม่จำเป็นต่อการเลือกประเทศ",
  ],
  [
    "Contact / Form",
    "Detailed message / specification notes",
    "Your message / specification details",
    "ข้อความ / รายละเอียด Specification",
    "สื่อสิ่งที่ต้องกรอกโดยตรงและรักษาศัพท์เทคนิค",
  ],
  [
    "Contact / Form",
    "Specify estimated production volumes, technical requirements (e.g., GSM, fibre blend, seam sealing), or desired audit schedule…",
    "Tell us your estimated quantity, technical requirements such as GSM or fibre blend, or preferred audit date…",
    "ระบุจำนวนผลิตโดยประมาณ ข้อกำหนดทางเทคนิค เช่น GSM หรือส่วนผสมเส้นใย หรือวันที่ต้องการนัด audit…",
    "ตัดตัวอย่าง seam sealing เพื่อไม่ให้เข้าใจว่ารองรับบริการนี้จาก placeholder เพียงอย่างเดียว",
  ],
  [
    "Contact / Form",
    "Buyer audit / certification binder",
    "Buyer audit / factory documents",
    "Buyer audit / เอกสารโรงงาน",
    "ไม่ทำให้เอกสารโรงงานทุกประเภทถูกเข้าใจว่าเป็น Certification",
  ],
  [
    "Contact / Form",
    "Dispatch desk message",
    "Send enquiry",
    "ส่งคำสอบถาม",
    "ให้ CTA ตรงกับการทำงานและใช้คำสม่ำเสมอ",
  ],
  [
    "Shared / Footer",
    "Garment OEM production for brands, from brief and sample review to cutting, sewing, decoration, quality checks and delivery. Discuss your materials, product details and order requirements with the TM Apparel team.",
    "OEM garment manufacturing for brands, from brief and sampling to cutting, sewing, decoration, QC and delivery. Talk to TM Apparel about your materials, garment details and order requirements.",
    "ผลิตเสื้อผ้า OEM สำหรับแบรนด์ ตั้งแต่บรีฟและ Sampling ไปจนถึงตัด เย็บ ตกแต่ง QC และส่งมอบ พูดคุยกับ TM Apparel เรื่อง Material รายละเอียดสินค้า และความต้องการในการสั่งผลิต",
    "ลดความยาวของ Footer และใช้คำกระบวนการให้สอดคล้องกับหน้าหลัก",
  ],
  [
    "Shared / Footer",
    "Capabilities Matrix",
    "Production capabilities",
    "ขอบเขตงานผลิต",
    "ลดศัพท์ matrix ที่ไม่จำเป็นต่อการนำทาง",
  ],
  [
    "Shared / Footer",
    "Machinery Roster",
    "Machinery & equipment",
    "เครื่องจักรและอุปกรณ์",
    "ตั้งชื่อลิงก์ตามเนื้อหาปลายทาง",
  ],
  [
    "Shared / Footer",
    "Enterprise Heritage",
    "Company history",
    "ประวัติบริษัท",
    "ใช้ชื่อประวัติบริษัทตรง ๆ แทนภาษาที่โอ่อ่า",
  ],
  [
    "Shared / Metadata",
    "Thonburi Master garment manufacturing, with OEM apparel services through TM Apparel. Explore materials, production and project enquiries.",
    "OEM garment manufacturing for Thai and international brands through TM Apparel, part of Thonburi Master. Explore materials, sampling, production and ways to start your project.",
    "Thonburi Master ให้บริการผลิตเสื้อผ้า OEM ผ่าน TM Apparel สำหรับแบรนด์ไทยและต่างประเทศ ดูข้อมูล Material, Sampling ขั้นตอนการผลิต และวิธีเริ่มโปรเจกต์",
    "บอกบริการ กลุ่มลูกค้า และเนื้อหาที่จะพบในเว็บไซต์อย่างกระชับ",
  ],
];
